[project]
name = "octicka"
version = "0.1.0"
description = "Cognitive Neuroscience Experiment Manager for Octave"
authors = ["iandol <iandol@cog5.org>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
octavegui = "octave --gui"

[dependencies]
octave = ">=9.3.0,<10"
gstreamer = ">=1.24.7,<2"
gst-plugins-bad = ">=1.24.7,<2"
fortran-compiler = ">=1.9.0,<2"
cxx-compiler = ">=1.9.0,<2"
make = ">=4.4.1,<5"
cmake = ">=3.31.6,<4"
gst-plugins-base = ">=1.24.7,<2"
gst-plugins-good = ">=1.24.7,<2"
gst-plugins-ugly = ">=1.24.7,<2"
graphicsmagick = ">=1.3.45,<2"
