[project]
name = "octicka"
version = "0.1.0"
description = "Cognitive Neuroscience Experiment Manager for Octave"
authors = ["iandol <iandol@cog5.org>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
octave = ">=9.2.0,<9.3"
gstreamer = ">=1.24.4,<1.25"
gst-plugins-bad = ">=1.24.4,<1.25"
fortran-compiler = ">=1.7.0,<1.8"
cxx-compiler = ">=1.7.0,<1.8"
make = ">=4.3,<5"
cmake = ">=3.30.0,<3.31"
gst-plugins-base = ">=1.24.4,<1.25"
gst-plugins-good = ">=1.24.4,<1.25"
gst-plugins-ugly = ">=1.24.4,<1.25"
graphicsmagick = ">=1.3.43,<1.4"
