## -*- texinfo -*-
## @deftypefn  {} {} dummy()
##
## This is a dummy function documentation. This file have a lot functions
## and each one have a little documentation. This text is to avoid a warning when
## install this file as part of package.
## @end deftypefn
##
## Set the graphics toolkit and force read this file as script file (not a function file).
##
graphics_toolkit qt;
##


##
##
## Begin callbacks definitions 
##

## @deftypefn  {} {} TouchTraining_StartButton_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of StartButton control.
##
## @end deftypefn
function TouchTraining_StartButton_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

tr.name = get(TouchTraining.SubjectName,'String');
tr.timeOut = str2num(get(TouchTraining.Timeout,'String'));
tr.phase = str2num(get(TouchTraining.Phase,'String'));
tr.bg = str2num(get(TouchTraining.BackgroundColour,'String'));
tr.fg = str2num(get(TouchTraining.TouchColour,'String'));
tr.minSize = str2num(get(TouchTraining.MinSize,'String'));
tr.maxSize = str2num(get(TouchTraining.MaxSize,'String'));
tr.distance = str2num(get(TouchTraining.Distance,'String'));
tr.density = str2num(get(TouchTraining.Density,'String'));
tr.task = get(TouchTraining.Task,'Value');
tr.folder = get(TouchTraining.Folder,'string');
tr.random = str2num(get(TouchTraining.Density,'String'));
tr.debug = logical(get(TouchTraining.Debug,'Value'));
tr.dummy = logical(get(TouchTraining.Dummy,'Value'));

startTouchTraining(tr);


end

## @deftypefn  {} {} TouchTraining_Load_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of Load control.
##
## @end deftypefn
function TouchTraining_Load_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

[f,p] = uigetfile('*.mat','Read Training Data');
if isnumeric(f); return; end

oldp = pwd;
cd(p);
load(f);
if exist('d','var')
    td = touchData();
    td.plot(d);
end
end

## @deftypefn  {} {} TouchTraining_startVideo_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of startVideo control.
##
## @end deftypefn
function TouchTraining_startVideo_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

pid = get(TouchTraining.startVideo,'TooltipString');
if ~isempty(pid); warning('Camera running...');return; end

pid = rpistreamer;
if ~isempty(pid);
	fprintf('===> RPi Video stream PID = %i activated!\n',pid);
	set(TouchTraining.startVideo,'String',sprintf('Started [%i]',pid));
	set(TouchTraining.startVideo,'TooltipString',sprintf('%i',pid));
end

end

## @deftypefn  {} {} TouchTraining_stopVideo_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of stopVideo control.
##
## @end deftypefn
function TouchTraining_stopVideo_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

pid = str2num(get(TouchTraining.startVideo,'TooltipString'));

if exist('pid','var') && ~isempty(pid)
	fprintf('===> Try to kill PID = %i\n',pid);	
	try
		system('pkill -9 libcamera-vid');
		system(['kill -9 ' num2str(pid+1)]);
		system(['kill -9 ' num2str(pid)]);
		system('pkill -9 libcamera-vid');
	end
	set(TouchTraining.startVideo,'String',sprintf('Start Video',pid));
	set(TouchTraining.startVideo,'Tooltipstring','');
end
end

 
## @deftypefn  {} {@var{ret} = } show_TouchTraining(varargin)
##
## Create windows controls over a figure, link controls with callbacks and return 
## a window struct representation.
##
## @end deftypefn
function ret = show_TouchTraining(varargin)
  _scrSize = get(0, "screensize");
  _xPos = (_scrSize(3) - 921)/2;
  _yPos = (_scrSize(4) - 705)/2;
   TouchTraining = figure ( ... 
	'Color', [0.937 0.937 0.937], ...
	'Position', [_xPos _yPos 921 705], ...
	'resize', 'off', ...
	'windowstyle', 'normal', ...
	'MenuBar', 'none');
	 set(TouchTraining, 'visible', 'off');
  Settings = uibuttongroup( ...
	'parent',TouchTraining, ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'BorderWidth', 1, ... 
	'FontAngle', 'italic', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 18, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.490 0.490 0.490], ... 
	'Position', [5 9 902 691], ... 
	'title', 'Touch Training Settings', ... 
	'TitlePosition', 'righttop', ... 
	'visible', 'on');
  StartButton = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.643 0.000 0.000], ... 
	'Position', [700 9 190 59], ... 
	'String', 'Start!', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  SubjectName = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 619 290 47], ... 
	'String', 'Test', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Phase = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 559 290 47], ... 
	'String', '1', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  BackgroundColour = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 439 290 47], ... 
	'String', '[0.2 0.2 0.2]', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  TouchColour = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 379 290 47], ... 
	'String', '[1 1 1]', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_1 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 626 256 30], ... 
	'String', 'Subject Name', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_2 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 566 256 30], ... 
	'String', 'Training Phase (1-20)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_3 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 446 256 30], ... 
	'String', 'Background Colour', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_4 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 386 256 30], ... 
	'String', 'Touch Colour', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Debug = uicontrol( ...
	'parent',Settings, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [705 71 184 40], ... 
	'String', 'Debug', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 0, ... 
	'visible', 'on');
  Load = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [10 10 180 56], ... 
	'String', 'Load', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  startVideo = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [240 10 180 56], ... 
	'String', 'Start Video', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  stopVideo = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [475 10 180 56], ... 
	'String', 'Stop Video', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Density = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [160 259 140 47], ... 
	'String', '80', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Distance = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 259 140 47], ... 
	'String', '25', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_5 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 266 256 30], ... 
	'String', 'Distance (cm) / Density (px/cm)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Timeout = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 499 290 47], ... 
	'String', '2', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_6 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 506 256 30], ... 
	'String', 'Timeout (secs)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Dummy = uicontrol( ...
	'parent',Settings, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [705 116 184 40], ... 
	'String', 'Dummy', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 0, ... 
	'visible', 'on');
  MaxSize = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [160 319 140 47], ... 
	'String', '35', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  MinSize = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 319 140 47], ... 
	'String', '4', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_7 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 326 256 30], ... 
	'String', 'Min/Max Size (deg)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Task = uicontrol( ...
	'parent',Settings, ... 
	'Style','popupmenu', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'italic', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [10 199 290 47], ... 
	'String', 'Standard|Simple|Pictures', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_8 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 206 256 30], ... 
	'String', 'Task Type', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Random = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 79 290 47], ... 
	'String', '0', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_9 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.937 0.937 0.937], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 86 256 30], ... 
	'String', 'Random Reward (secs)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Folder = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.192 0.216 0.224], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [10 139 290 47], ... 
	'String', '/media/cog/data/Media/MP', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_10 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.929 0.929 0.929], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.192 0.216 0.224], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [305 146 256 30], ... 
	'String', 'Folder for Pictures', ... 
	'TooltipString', '', ... 
	'visible', 'on');

  TouchTraining = struct( ...
      'figure', TouchTraining, ...
      'Settings', Settings, ...
      'StartButton', StartButton, ...
      'SubjectName', SubjectName, ...
      'Phase', Phase, ...
      'BackgroundColour', BackgroundColour, ...
      'TouchColour', TouchColour, ...
      'Label_1', Label_1, ...
      'Label_2', Label_2, ...
      'Label_3', Label_3, ...
      'Label_4', Label_4, ...
      'Debug', Debug, ...
      'Load', Load, ...
      'startVideo', startVideo, ...
      'stopVideo', stopVideo, ...
      'Density', Density, ...
      'Distance', Distance, ...
      'Label_5', Label_5, ...
      'Timeout', Timeout, ...
      'Label_6', Label_6, ...
      'Dummy', Dummy, ...
      'MaxSize', MaxSize, ...
      'MinSize', MinSize, ...
      'Label_7', Label_7, ...
      'Task', Task, ...
      'Label_8', Label_8, ...
      'Random', Random, ...
      'Label_9', Label_9, ...
      'Folder', Folder, ...
      'Label_10', Label_10);


  set (StartButton, 'callback', {@TouchTraining_StartButton_doIt, TouchTraining});
  set (Load, 'callback', {@TouchTraining_Load_doIt, TouchTraining});
  set (startVideo, 'callback', {@TouchTraining_startVideo_doIt, TouchTraining});
  set (stopVideo, 'callback', {@TouchTraining_stopVideo_doIt, TouchTraining});
  dlg = struct(TouchTraining);

  set(TouchTraining.figure, 'visible', 'on');

%
% The source code written here will be executed when
% windows load. Works like 'onLoad' event of other languages.
%



  ret = TouchTraining;
end

