## -*- texinfo -*-
## @deftypefn  {} {} dummy()
##
## This is a dummy function documentation. This file have a lot functions
## and each one have a little documentation. This text is to avoid a warning when
## install this file as part of package.
## @end deftypefn
##
## Set the graphics toolkit and force read this file as script file (not a function file).
##
graphics_toolkit qt;
##


##
##
## Begin callbacks definitions 
##

## @deftypefn  {} {} TouchTraining_StartButton_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of StartButton control.
##
## @end deftypefn
function TouchTraining_StartButton_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

tr.name = get(TouchTraining.SubjectName,'String');
tr.timeOut = str2num(get(TouchTraining.Timeout,'String'));
tr.phase = str2num(get(TouchTraining.Phase,'String'));
tr.bg = str2num(get(TouchTraining.BackgroundColour,'String'));
tr.fg = str2num(get(TouchTraining.TouchColour,'String'));
tr.minSize = str2num(get(TouchTraining.MinSize,'String'));
tr.maxSize = str2num(get(TouchTraining.MaxSize,'String'));
tr.distance = str2num(get(TouchTraining.Distance,'String'));
tr.density = str2num(get(TouchTraining.Density,'String'));
tr.volume = str2num(get(TouchTraining.Volume,'String'));
tr.random = str2num(get(TouchTraining.Random,'String'));
tr.soundvol = str2num(get(TouchTraining.SoundVol,'String'));
tr.audio = logical(get(TouchTraining.AudioEnabled,'Value'));
tr.task = get(TouchTraining.Task,'Value');
tr.stimulus = get(TouchTraining.Stimulus,'Value');
tr.folder = get(TouchTraining.Folder,'string');
tr.rewardmode = get(TouchTraining.RewardMode,'Value');
switch tr.rewardmode
case 1
	tr.rewardmode = 'pigpiod';
case 2
	tr.rewardmode = 'wiringpi';
otherwise
	tr.rewardmode = 'legacy';
end
tr.debug = logical(get(TouchTraining.Debug,'Value'));
tr.dummy = logical(get(TouchTraining.Dummy,'Value'));

startTouchTraining(tr);


end

## @deftypefn  {} {} TouchTraining_Load_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of Load control.
##
## @end deftypefn
function TouchTraining_Load_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

[f,p] = uigetfile('*.mat','Read Training Data');
if isnumeric(f); return; end

oldp = pwd;
cd(p);
load(f);
if exist('d','var')
    td = touchData();
    td.plot(d);
end
end

## @deftypefn  {} {} TouchTraining_startVideo_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of startVideo control.
##
## @end deftypefn
function TouchTraining_startVideo_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

pid = get(TouchTraining.startVideo,'TooltipString');
if ~isempty(pid); warning('Camera running...');return; end

pid = rpistreamer;
if ~isempty(pid);
	fprintf('===> RPi Video stream PID = %i activated!\n',pid);
	set(TouchTraining.startVideo,'String',sprintf('Started [%i]',pid));
	set(TouchTraining.startVideo,'TooltipString',sprintf('%i',pid));
end

end

## @deftypefn  {} {} TouchTraining_stopVideo_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of stopVideo control.
##
## @end deftypefn
function TouchTraining_stopVideo_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

pid = str2num(get(TouchTraining.startVideo,'TooltipString'));

if exist('pid','var') && ~isempty(pid)
	fprintf('===> Try to kill PID = %i\n',pid);	
	try
		system('pkill -9 libcamera-vid');
		system(['kill -9 ' num2str(pid+1)]);
		system(['kill -9 ' num2str(pid)]);
		system('pkill -9 libcamera-vid');
	end
	set(TouchTraining.startVideo,'String',sprintf('Start Video',pid));
	set(TouchTraining.startVideo,'Tooltipstring','');
end
end

## @deftypefn  {} {} TouchTraining_Volume_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of Volume control.
##
## @end deftypefn
function TouchTraining_Volume_doIt(src, data, TouchTraining)

% This code will be executed when de control lost focus and text has
% been changed or when press the enter key
% As default, all events are deactivated, to activate must set the
% property 'generateCallBack' from the properties editor

v = 9.38e-4;
vol = str2num(get(TouchTraining.Volume,'String'));
vv = vol * v;
set(TouchTraining.volamount,'String',[num2str(vv) ' ml']);

end

## @deftypefn  {} {} TouchTraining_Button_5_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of Button_5 control.
##
## @end deftypefn
function TouchTraining_Button_5_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

p = uigetdir;
if ischar(p)
  set(TouchTraining.Folder,'String',p);
end
end

## @deftypefn  {} {} TouchTraining_RewardTest_doIt (@var{src}, @var{data}, @var{TouchTraining})
##
## Define a callback for default action of RewardTest control.
##
## @end deftypefn
function TouchTraining_RewardTest_doIt(src, data, TouchTraining)

% This code will be executed when user click the button control.
% As default, all events are deactivated, to activate must set the
% property 'generateCallback' from the properties editor

audio = logical(get(TouchTraining.AudioEnabled,'Value'));
mode = get(TouchTraining.RewardMode,'Value');
switch mode
case 1
	mode = 'pigpiod';
case 2
	mode = 'wiringpi';
otherwise
	mode = 'legacy';
end
if audio
	aM = audioManager;
	aM.open;
	aM.beep;
end
rM = gpioManager('mode', mode);
rM.open;
rM.giveReward;
if audio; aM.beep; aM.close; end
rM.reset;

end

 
## @deftypefn  {} {@var{ret} = } show_TouchTraining(varargin)
##
## Create windows controls over a figure, link controls with callbacks and return 
## a window struct representation.
##
## @end deftypefn
function ret = show_TouchTraining(varargin)
  _scrSize = get(0, "screensize");
  _xPos = (_scrSize(3) - 1000);
  _yPos = 398;
   TouchTraining = figure ( ... 
	'Color', [0.941 0.941 0.941], ...
	'Position', [_xPos _yPos 1000 652], ...
	'resize', 'off', ...
	'windowstyle', 'normal', ...
	'MenuBar', 'none');
	 set(TouchTraining, 'visible', 'off');
  Settings = uibuttongroup( ...
	'parent',TouchTraining, ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'BorderWidth', 1, ... 
	'FontAngle', 'italic', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 18, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.490 0.490 0.490], ... 
	'Position', [5 33 986 614], ... 
	'title', 'Touch Training Settings', ... 
	'TitlePosition', 'righttop', ... 
	'visible', 'on');
  StartButton = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.867 0.867 0.867], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.643 0.000 0.000], ... 
	'Position', [795 5 184 59], ... 
	'String', 'Start!', ... 
	'TooltipString', 'Start training session', ... 
	'visible', 'on');
  SubjectName = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [5 532 290 47], ... 
	'String', 'Test', ... 
	'TooltipString', 'Subject Name', ... 
	'visible', 'on');
  Phase = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [460 532 290 47], ... 
	'String', '1', ... 
	'TooltipString', 'Phase of the task', ... 
	'visible', 'on');
  BackgroundColour = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [5 392 290 47], ... 
	'String', '[0.2 0.2 0.2]', ... 
	'TooltipString', 'Background colour', ... 
	'visible', 'on');
  TouchColour = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [460 392 290 47], ... 
	'String', '[1 1 1]', ... 
	'TooltipString', 'Target colour', ... 
	'visible', 'on');
  Label_1 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [299 542 93 22], ... 
	'String', 'Subject Name', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_2 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [755 542 140 22], ... 
	'String', 'Training Phase (1-20)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_3 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [300 402 129 22], ... 
	'String', 'Background Colour', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_4 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [755 407 89 22], ... 
	'String', 'Touch Colour', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Debug = uicontrol( ...
	'parent',Settings, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [795 69 184 40], ... 
	'String', 'Debug', ... 
	'TooltipString', 'for debugging', ... 
	'Min', 0, 'Max', 1, 'Value', 0, ... 
	'visible', 'on');
  Load = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.867 0.867 0.867], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [5 8 180 56], ... 
	'String', 'Load Data', ... 
	'TooltipString', 'Load previous data', ... 
	'visible', 'on');
  startVideo = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.867 0.867 0.867], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [385 8 180 56], ... 
	'String', 'Start Video', ... 
	'TooltipString', 'Start RPi camera', ... 
	'visible', 'on');
  stopVideo = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.867 0.867 0.867], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [575 8 180 56], ... 
	'String', 'Stop Video', ... 
	'TooltipString', 'Stop Rpi camera', ... 
	'visible', 'on');
  Density = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [610 322 140 47], ... 
	'String', '80', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Distance = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [460 322 140 47], ... 
	'String', '25', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_5 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [755 337 206 22], ... 
	'String', 'Distance (cm) / Density (px/cm)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Timeout = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [5 462 290 47], ... 
	'String', '4', ... 
	'TooltipString', 'Time out during incorrect trials', ... 
	'visible', 'on');
  Label_6 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [300 477 98 22], ... 
	'String', 'Timeout (secs)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Dummy = uicontrol( ...
	'parent',Settings, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.941 0.941 0.941], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [795 114 184 40], ... 
	'String', 'Dummy', ... 
	'TooltipString', 'if no real touch screen is attached', ... 
	'Min', 0, 'Max', 1, 'Value', 0, ... 
	'visible', 'on');
  MaxSize = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [155 322 140 47], ... 
	'String', '35', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  MinSize = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [5 322 140 47], ... 
	'String', '4', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_7 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [300 337 125 22], ... 
	'String', 'Min/Max Size (deg)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Task = uicontrol( ...
	'parent',Settings, ... 
	'Style','popupmenu', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.902 0.902 0.902], ... 
	'FontAngle', 'italic', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'Position', [5 252 290 47], ... 
	'String', 'Simple|Standard', ... 
	'TooltipString', 'Task difficulty - simple=9 phases | standard = 20 phases', ... 
	'visible', 'on');
  Label_8 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [300 262 93 22], ... 
	'String', 'Task Difficulty', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Random = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [460 462 140 47], ... 
	'String', '0', ... 
	'TooltipString', 'Time to give random reward (secs)', ... 
	'visible', 'on');
  Label_9 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.000 0.000 0.000], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [755 487 204 22], ... 
	'String', 'Randomise / Reward Time(ms)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Folder = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.192 0.216 0.224], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [5 182 290 47], ... 
	'String', '/media/cog/data/Media/General-Fruit', ... 
	'TooltipString', 'Folder for pictures', ... 
	'visible', 'on');
  Label_10 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.192 0.216 0.224], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [300 202 122 22], ... 
	'String', 'Folder for Pictures', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Volume = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.192 0.216 0.224], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [610 462 140 47], ... 
	'String', '250', ... 
	'TooltipString', 'Time to drive reward pump', ... 
	'visible', 'on');
  Stimulus = uicontrol( ...
	'parent',Settings, ... 
	'Style','popupmenu', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.902 0.902 0.902], ... 
	'FontAngle', 'italic', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.192 0.216 0.224], ... 
	'Position', [460 252 290 47], ... 
	'String', 'Disc|Picture', ... 
	'TooltipString', 'Disc or Picture stimulus', ... 
	'visible', 'on');
  Label_11 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.941 0.941 0.941], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [755 267 94 22], ... 
	'String', 'Stimulus Type', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  volamount = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 11, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.192 0.216 0.224], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [755 464 112 20], ... 
	'String', '0.23333333333 ml', ... 
	'TooltipString', 'Estimated volume of reward', ... 
	'visible', 'on');
  SoundVol = uicontrol( ...
	'parent',Settings, ... 
	'Style','edit', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [1.000 1.000 1.000], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Fira Code', ... 
	'FontSize', 13, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.192 0.216 0.224], ... 
	'HorizontalAlignment', 'center', ... 
	'Position', [460 182 290 47], ... 
	'String', '0.75', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Label_13 = uicontrol( ...
	'parent',Settings, ... 
	'Style','text', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.940 0.940 0.940], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'HorizontalAlignment', 'left', ... 
	'Position', [755 207 126 22], ... 
	'String', 'Audio Volume (0-1)', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  Button_5 = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.941 0.941 0.941], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'bold', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [300 185 19 19], ... 
	'String', '?', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  RewardTest = uicontrol( ...
	'parent',Settings, ... 
	'Style','pushbutton', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.867 0.867 0.867], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 14, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [195 8 180 56], ... 
	'String', 'Test Reward', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  RewardMode = uicontrol( ...
	'parent',Settings, ... 
	'Style','popupmenu', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.929 0.925 0.922], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 12, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [195 69 180 25], ... 
	'String', 'pigpiod|wiringpi|legacy', ... 
	'TooltipString', '', ... 
	'visible', 'on');
  AudioEnabled = uicontrol( ...
	'parent',Settings, ... 
	'Style','checkbox', ... 
	'Units', 'pixels', ... 
	'BackgroundColor', [0.941 0.941 0.941], ... 
	'FontAngle', 'normal', ... 
	'FontName', 'Source Sans 3', ... 
	'FontSize', 10, 'FontUnits', 'points', ... 
	'FontWeight', 'normal', ... 
	'ForegroundColor', [0.102 0.102 0.102], ... 
	'Position', [750 182 113 27], ... 
	'String', 'Enable Audio?', ... 
	'TooltipString', '', ... 
	'Min', 0, 'Max', 1, 'Value', 1, ... 
	'visible', 'on');

  TouchTraining = struct( ...
      'figure', TouchTraining, ...
      'Settings', Settings, ...
      'StartButton', StartButton, ...
      'SubjectName', SubjectName, ...
      'Phase', Phase, ...
      'BackgroundColour', BackgroundColour, ...
      'TouchColour', TouchColour, ...
      'Label_1', Label_1, ...
      'Label_2', Label_2, ...
      'Label_3', Label_3, ...
      'Label_4', Label_4, ...
      'Debug', Debug, ...
      'Load', Load, ...
      'startVideo', startVideo, ...
      'stopVideo', stopVideo, ...
      'Density', Density, ...
      'Distance', Distance, ...
      'Label_5', Label_5, ...
      'Timeout', Timeout, ...
      'Label_6', Label_6, ...
      'Dummy', Dummy, ...
      'MaxSize', MaxSize, ...
      'MinSize', MinSize, ...
      'Label_7', Label_7, ...
      'Task', Task, ...
      'Label_8', Label_8, ...
      'Random', Random, ...
      'Label_9', Label_9, ...
      'Folder', Folder, ...
      'Label_10', Label_10, ...
      'Volume', Volume, ...
      'Stimulus', Stimulus, ...
      'Label_11', Label_11, ...
      'volamount', volamount, ...
      'SoundVol', SoundVol, ...
      'Label_13', Label_13, ...
      'Button_5', Button_5, ...
      'RewardTest', RewardTest, ...
      'RewardMode', RewardMode, ...
      'AudioEnabled', AudioEnabled);


  set (StartButton, 'callback', {@TouchTraining_StartButton_doIt, TouchTraining});
  set (Load, 'callback', {@TouchTraining_Load_doIt, TouchTraining});
  set (startVideo, 'callback', {@TouchTraining_startVideo_doIt, TouchTraining});
  set (stopVideo, 'callback', {@TouchTraining_stopVideo_doIt, TouchTraining});
  set (Volume, 'callback', {@TouchTraining_Volume_doIt, TouchTraining});
  set (Button_5, 'callback', {@TouchTraining_Button_5_doIt, TouchTraining});
  set (RewardTest, 'callback', {@TouchTraining_RewardTest_doIt, TouchTraining});
  dlg = struct(TouchTraining);

  set(TouchTraining.figure, 'visible', 'on');

%
% The source code written here will be executed when
% windows load. Works like 'onLoad' event of other languages.
%
ver = 1.12;
v = 9.38e-4;
vol = str2num(get(TouchTraining.Volume,'String'));
vv = vol * v;
set(TouchTraining.volamount,'String',[num2str(vv) ' ml']);
set(TouchTraining.Settings,'Title',['Touch Training V' num2str(ver)]);
set(TouchTraining.figure,'name',['Touch Training V' num2str(ver)]);









  ret = TouchTraining;
end

